project:
  type: website
  output-dir: docs

website:
  favicon: favicon.ico
  title: "Mastering Python"
  reader-mode: false
  open-graph: true
  google-analytics: 
    tracking-id: 'G-HE366VCQBM'
  site-url: 'https://py.muthu.co'
  site-path: '/'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muthuspark
      - icon: twitter
        href: https://twitter.com/krimuthu
format:
  html:
    theme: litera
    css: styles.css
    lang: en
    toc: true
    image: false
    mermaid:
      theme: neutral
    include-after-body:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3609399560636561" crossorigin="anonymous"></script>



